Added task sort feature
IEEE-VIT/ToDo-iOS pull request #35
Opened 2020-10-02 11:27 UTC by er-aman-gupta

### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes #6 

### Type of Change:
**Delete irrelevant options.**

- Code
- User Interface

### How Has This Been Tested?
Tested on Iphone 11 pro max simulator, by creating a couple of task and sorting them one by one with the available options, the sorted list is in accordance with the sort selected

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

2020-10-02 12:59 UTC, aaryankotharii commented
Hey @er-aman-gupta Great work! you picked the perfect symbol for the bar button and action sheet is exactly as expected. There is one minor bug which though which I will be explaining in the review below.

2020-10-02 13:21 UTC, aaryankotharii requested changes

2020-10-02 13:21 UTC, aaryankotharii commented on Application/To-Do/Controller/TodoViewController.swift
> +                task1.dueDate < task2.dueDate
the dueDate property of a task is currently is string, hence 
```Swift
task1.dueDate < task2.dueDate
```
will sort the dates alphabetically and not chronologically.
eg: 01/02/2021 will come before 09/10/2020 but it should come after.

- solution 1: change the data type to Date and make the requisite changes wherever required.


- solution 2: use a `DateFormatter' with the dateFormat as `MM/dd/yyyy hh:mm a`, convert the dueDate to Date and then sort.

you can choose any solution based on what you think is optimum.
Please re request a review once done.
Thank you 😄

2020-10-02 13:21 UTC, aaryankotharii commented on Application/To-Do/Controller/TodoViewController.swift
> +enum SortTypesAvailable: CaseIterable {
Lastly, we can add a new file named `SortTypes.swift` in the Model directory and shift this enum there.

2020-10-02 13:33 UTC, aaryankotharii commented
@er-aman-gupta Since we are moving our database to coreData, this pr will be merged before #34 to avoid any inconstancies here.

2020-10-02 15:25 UTC, er-aman-gupta commented on Application/To-Do/Controller/TodoViewController.swift
> +                task1.dueDate < task2.dueDate
hey, i have added a new field named `dueDateTimeStamp` in the `Task` model to avoid conversion each time we sort. and now we sort according to those timestamps. Thanks for pointing this out 😀

2020-10-02 15:25 UTC, er-aman-gupta commented on Application/To-Do/Controller/TodoViewController.swift
> +enum SortTypesAvailable: CaseIterable {
Added the file

2020-10-02 17:06 UTC, aaryankotharii commented
Hey @er-aman-gupta since now we have shifted the database to coreData, the functionality of sorting has to be taken up by fetchedResultsController. we already have it have a method named `setupFetchedResultsController` you just need to call that function in the buttons to your action sheet.
for example :
if user taps Sort By Date (Earliest first)
call this function 
```Swift
let fetchRequest : NSFetchRequest<Task> = Task.fetchRequest()
fetchRequest.sortDescriptors = [NSSortDescriptor(key: "dueDateTimeStamp", ascending: true)]
setupFetchedResultsController(fetchRequest: fetchRequest)
```

2020-10-03 09:01 UTC, er-aman-gupta commented
Hi @aaryankotharii , thanks for pointing it out that i can use core data to sort the data. This was my first time working with core data😅.

2020-10-03 09:21 UTC, aaryankotharii commented
Hey @er-aman-gupta , Great work! I am very glad that you have leaned something new while woking on this repository and proficiently solved the issue. Thank you for your contribution and feel free to add/pick-up more issues here.
Approved.

2020-10-03 09:22 UTC, aaryankotharii approved these changes

2020-10-03 09:22 UTC, merged